# Comment savoir si c'est une copie ou une vue?

In [2]:
import numpy as np

def is_base(a):
    return a.base is None

def is_view(a):
    return not (a.base is None)

def memory_shared(a, b):
    return np.shares_memory(a, b)

a=np.arange(10)
b=a[0:4]
c=a[4:]
cpy=a[4:].copy()

print(a)
print(a.base) # Base object if memory is from some other object

print('-'*40)

if is_base(a):  # if a.base is None:
    print("il n'y a pas d'objet ayant servi à construire a")

if is_base(b):  # if b.base is None:
    print("il n'y a pas d'objet ayant servi à construire b")
    
if b.base is a:
    print("a a servi à construire b")
    
if cpy.base is a:
    print("a a servi à construire cpy")
 
print('\n === Partage mémoire ===')

print("a et b   ", memory_shared(a, b))
print("a et c   ", memory_shared(a, c))
print("b et c   ", memory_shared(b, c))
print("c et cpy ", memory_shared(c, cpy))

print('-'*40)
b[0]=-1
print(a)

print('-'*40)

print('isbase(a)   : ', is_base(a))
print('isbase(b)   : ', is_base(b))
print('isbase(c)   : ', is_base(c))
print('isbase(cpy) : ', is_base(cpy))

print('-'*40)

a=c
print("mem shared a et c   ", memory_shared(a, c))
print('isbase(a)   : ', is_base(a))
print('isbase(c)   : ', is_base(c))

print('-'*40)
c[4]=-1
print(c)
print(a)

print('-'*40)
a[4]=42
print(c)
print(a)

print('is_view(a)   : ', is_view(a))
print('is_view(c)   : ', is_view(c))


[0 1 2 3 4 5 6 7 8 9]
None
----------------------------------------
il n'y a pas d'objet ayant servi à construire a
a a servi à construire b

 === Partage mémoire ===
a et b    True
a et c    True
b et c    False
c et cpy  False
----------------------------------------
[-1  1  2  3  4  5  6  7  8  9]
----------------------------------------
isbase(a)   :  True
isbase(b)   :  False
isbase(c)   :  False
isbase(cpy) :  True
----------------------------------------
mem shared a et c    True
isbase(a)   :  False
isbase(c)   :  False
----------------------------------------
[ 4  5  6  7 -1  9]
[ 4  5  6  7 -1  9]
----------------------------------------
[ 4  5  6  7 42  9]
[ 4  5  6  7 42  9]
is_view(a)   :  True
is_view(c)   :  True
