# Bibliothèque Python Numpy

Le module le plus important en python scientifique est nommé numpy. Ce module est une extension du langage de programmation Python, pour
manipuler des matrices ou des tableaux multidimensionnels.
Elle possède des fonctions mathématiques vectorielles opérant sur les tableaux.

### Exemples de création d'un tableau

* Un tableau numpy est mutable et itérable.
* Tous les éléments d'un tableau numpy sont du même type.
* On a un accès direct à un élément grâce à l'opérateur []. __La numérotation commence à zéro__.
* La variable membre dtype retourne le type des éléments.

In [ ]:
# OBLIGATOIRE importation du module numpy => np est un alias
import numpy as np

# tableau de zeros de type réel
z =np.zeros(shape=(2,), dtype='float')
print('zeros : ', z)
print('type du tableau : ', z.dtype) # dtype contient le type des éléments du tableau

# tableau de uns de type entier
u =np.ones(shape=(2, ), dtype='int')
print('uns : ', u)
print('type du tableau : ', u.dtype)

* Exercice : 
1. Créer un tableau d'entiers z de dimensions 2x4 rempli de zeros.
2. z.shape donne les dimensions du tableau sous la forme d'un tuple. Tester-le
2. Un tableau numpy est mutable. La valeur placée en [i,j] est modifiable
en tapant z[i,j] = valeur. Faire quelques essais.

In [ ]:
# A COMPLETER

### Autres Créations à partir d'une liste, d'une séquence, d'un intervalle

In [ ]:
# A partir d'une liste
a = np.asarray([1, 2, 3, 4], dtype='int') # ou utiliser np.array moins efficace
print("a partir d'une liste : ", a)
print('type du tableau : ', a.dtype)

# A partir d'une séquence
d = np.linspace(0, 1, 5)
print('sequence équi-espacée: ', d)
print('type du tableau : ', d.dtype)

# A partir d'un intervalle
b = np.arange(0, 1, 0.25)
print('intervalle équi-espacée: ', b)
print('type du tableau : ', d.dtype)


# Tranche de tableau : slicing

Le découpage (slicing) d'un tableau unidimensionnel NumPy est identique à celui d'une liste Python

* Exercice :
1. Créer un tableau de 10 entiers a avec la fonction arange commençant à zéro.
2. Afficher la tranche du 5eme élément au 8eme élément inclu. 

In [ ]:
# A COMPLETER

* Opérations plus avancées

In [ ]:
# extraction des elements avec un pas de 2 jusqu'a l'indice 8 exclu
print(a[:8:2])  
# renverse le tableau
print(a[::-1])   
print(a[-1::-1])

# Arithmétique sur tableau
L’intérêt des tableau numpy par rapport aux listes réside entre-autre dans le fait qu’il est possible de faire de l’arithmétique sur des tableaux.

In [ ]:
import numpy as np
a=np.arange(10, dtype='float')
print(a)
a=a+1      # ajout de 1 à tous les elements
print(a)
print(2*a) 
print(a*a) # carre de chaque element
print(a/a) # division element par element  DANGER

* Exercice :
1. Créer un tableau a de taille 2x2 contenant [1, 2] sur la première ligne et [3, 4] sur la seconde.
2. Faites a * a puis a @ a  . Expliquez le résultat obtenu.

In [ ]:
# A COMPLETER

# Fonctions vectorielles sur tableau
Appliquer des fonctions mathématiques (sin, exp, ...) aux tableaux. Là encore, la fonction
est appliquée __élément par élément__ à tous les éléments du tableau.

In [ ]:
x=np.linspace(0, 2*np.pi, 5)
print(x)
print(np.sin(x))

* Exercice :
Calculer pour chaque valeur du tableau x, y1=3cos(x)+sin(x) puis y2=cos(x)**2+sin(x)**2

In [ ]:
y1=3*np.cos(x)+np.sin(x)
print(y1)
y2 = np.cos(x)**2 + np.sin(x)**2
print(y2)

# Reformattage d'un tableau unidimensionnel en bidimensionnel
Pour transformer par exemple un tableau s de 12 éléments en un tableau r de 2 lignes de 6 éléments, on utilise la fonction membre reshape. __ATTENTION__ : reshape retourne une vue du tableau s.

In [ ]:
s=np.arange(12)
print(s)
r = s.reshape(2, 6) # r est une vue de s, ils occupent la même place en mémoire
print('après reshape \n', r)

# Aplattissage de tableaux
les fonctions ravel et flatten ont le même effet d’aplatir le tableau multi-dimensionnel r en un tableau unidimensionnel que l'on note a, mais la première est une fonction générale alors que la seconde est une méthode.
__ATTENTION__ : ravel retourne une vue du tableau alors que flatten() produit une copie du tableau.

In [ ]:
v = np.ravel(r) # v est une vue de r, ils occupent la même place en mémoire
b = r.flatten() # copie de r, ils ne sont pas à la même place en mémoire.
print(v)
print(b)

print('-'*50)

r[0, 0]=255
print(v) # ATTENTION a est modifié 

* Exercice : modifier la première valeur de v, r est aussi modifié

### Comment savoir si un tableau numpy une copie ou une vue?
Dans ce cas, r partage la mémoire allouée au tableau v. Ainsi np.shares_memory(v, r) retourne True.


In [ ]:
print(np.shares_memory(v,r))

### Comment faire une copie d'un tableau
Utiliser la fonction membre copy()

In [ ]:
c = v.copy()
print(np.shares_memory(c, v))
print(np.shares_memory(c, r))

# Concaténation de tableaux
Soient 2 tableaux a et b, comportant le même nombre de ligne, on désire construire le tableau augmenté a | b

In [ ]:
a=np.arange(12).reshape(3, 4)
b=a+10
print('tableau a'+'-'*20)
print(a)
print('tableau b'+'-'*20)
print(b)
print('tableau hs'+'-'*20)
hs=np.hstack((a, b))
print(hs)

Autre approche avec np.concatenate

In [ ]:
np.concatenate((a, b), axis=1)

Généralisation suivant les autres directions

In [6]:
a=np.arange(12).reshape(3, 4)
b=a+10
vs=np.vstack((a, b))
print(vs)
print('-'*20)
ds=np.dstack((a, b))
print(ds)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
--------------------
[[[ 0 10]
  [ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 8 18]
  [ 9 19]
  [10 20]
  [11 21]]]


# Itérer sur un tableau bidimensionnel

In [8]:
# premiere methode
a=np.arange(12).reshape(3, 4)
Nrows, Ncols = a.shape # recuperation du nombre de lignes et de colonnes
for i in range(Nrows):
    for j in range(Ncols):
        print(i, j, a[i,j])

0 0 0
0 1 1
0 2 2
0 3 3
1 0 4
1 1 5
1 2 6
1 3 7
2 0 8
2 1 9
2 2 10
2 3 11


Avant de développer une autre approche, regardons ce que donne :

In [15]:
# A Analyser
print(list(enumerate(a))) # expliquer

print('-'*20)
for nrow, row in enumerate(a):
    print(nrow, '=>', row)

[(0, array([0, 1, 2, 3])), (1, array([4, 5, 6, 7])), (2, array([ 8,  9, 10, 11]))]
--------------------
0 => [0 1 2 3]
1 => [4 5 6 7]
2 => [ 8  9 10 11]


* Exercice : comprendre la méthode décrite ci-dessous:

In [14]:
# seconde methode
for nrow, row in enumerate(a):
    for ncol, val in enumerate(row):
        print(nrow, ncol, '=>', val)

0 0 => 0
0 1 => 1
0 2 => 2
0 3 => 3
1 0 => 4
1 1 => 5
1 2 => 6
1 3 => 7
2 0 => 8
2 1 => 9
2 2 => 10
2 3 => 11


# Protéger un tableau numpy de l'écriture
Autrement dit, les éléments du tableau sont seulement accessibles en lecture.
Impossible de modifier ses valeurs.

In [16]:
import numpy as np
a=np.arange(10)
a.setflags(write=False) # protection en écriture
print('lecture ', a[0])
try:
    a[0]=1
except ValueError:
    print('a[0]=1')
    print('a est protégé en écriture')

lecture  0
a[0]=1
a est protégé en écriture
